name: Deploy To Stage

on:
  push:
    branches: 
      - '*'
# on:
#   pull_request:
#     types: [closed]
#     # branches: [main]
#     branches: 
#       - main
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ENDPOINT_URL: 'https://appstage.dwayremit.com/v2'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Packages and Build Application
        run: |
          npm install
          VITE_ENV=staging VITE_USER_SERVICE_URL="${ENDPOINT_URL}" npm run build

      - name: Commit built assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B sandboxDeployment
         
           git rm -r .github
          git rm -r README.md
          git rm -r public
          git rm bun.lockb
          git rm components.json
          git rm eslint.config.js
          git rm index.html
          git rm package-lock.json
          git rm package.json
          git rm postcss.config.js
          git rm tailwind.config.ts
          git rm tsconfig.app.json
          git rm -r tsconfig.node.json
          git rm -r vite.config.ts
          git rm -r vitest.config.ts
          git rm -r src
          git rm .env
          git add .
          git commit -m "Build Staging"
          git push -f origin sandboxDeployment

      - name: Deploy via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: 'dist/*'
          target: /var/www/payoutsandbox
